# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

stages:
  - build
  - test
  - deploy

pages:
  image: node:latest
  stage: deploy # List of stages for jobs, and their order of execution
  script:
    - npm install --progress=false
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    #
    - echo "Running "
    - echo "Content of the file" >public/dtest.json
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - master
    - 12-vocab-pipeline-initial-setup

#defaultVoc:
#  image: node:latest
#  stage: build
#  script:
#    - echo "It works."
#    - echo "Writing to file" >dtest.json
#  artifacts:
#    paths:
#      - dtest.json
